---

dependency:
  name: galaxy
driver:
  name: vagrant
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: molecule-vagrant-centos7-bento
    box: bento/centos-7
    memory: 512
    cpus: 1
    provider_options:
      gui: false
  - name: molecule-vagrant-ubuntu-18.04
    box: bento/ubuntu-18.04
    memory: 512
    cpus: 1
    provider_options:
      gui: false
  - name: molecule-vagrant-archlinux
    box: archlinux/archlinux
    memory: 512
    cpus: 1
    provider_options:
      gui: false
  - name: molecule-vagrant-kalilinux
    box: kalilinux/rolling
    memory: 512
    cpus: 1
    provider_options:
      gui: false
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  # options:
  #   become: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy