# Usage:

FROM {{cookiecutter.docker_image_name}}:{{cookiecutter.docker_image_tag}}
LABEL maintainer="{{cookiecutter.maintainer_name}} <{{cookiecutter.maintainer_email}}>"

# Username
ENV USER={{cookiecutter.docker_user}}
ENV UID=12345
ENV GID=23456


ENV TERM xterm-256color

# Set Shell
SHELL ["/bin/sh", "-o", "pipefail", "-c"]

RUN apk add --no-cache \
    bash git make curl sudo tmux curl shadow gnupg zsh wget vim nano emacs \
    nmap nmap-scripts \
    perl \
    perl-net-ssleay

RUN addgroup "$USER" --system &&\
    adduser \
    --disabled-password \
    --gecos "User" \
    --home "/home/$USER" \
    --ingroup "$USER" \
    -s /bin/zsh \
    --uid "$UID" \
    "$USER"

RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers


USER $USER

RUN wget -q https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh

WORKDIR "/home/$USER"

ENTRYPOINT ["{{cookiecutter.entrypoint }}"]